In [2]:
import numpy
my_list=[10,20,30,40,50]
arr=numpy.array(my_list)
arr

array([10, 20, 30, 40, 50])

In [7]:
import numpy
my_list=[10,20,30,40,50]
arr=numpy.array(my_list)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

5
int32
1
(5,)


In [8]:
import numpy
my_list=[[10,20,30],[40,50,60],[70,80,90]]
matrix=numpy.array(my_list)
print(matrix)
print(matrix.size)
print(matrix.dtype)
print(matrix.ndim)
print(matrix.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
9
int32
2
(3, 3)


In [9]:
import numpy as np
my_list=[10,20,30,40,50]
arr=np.array(my_list)
print("Elements:")
for ele in arr:
    print(ele)

Elements:
10
20
30
40
50


In [10]:
import numpy as np
my_list=[[10,20,30],[40,50,60],[70,80,90]]
matrix=np.array(my_list)
print("elements:")
print(matrix)

elements:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
import numpy as np
my_list=[[10,20,30],[40,50,60],[70,80,90]]
matrix=np.array(my_list)
print("elements:")
for row in matrix:
    print(row)

elements:
[10 20 30]
[40 50 60]
[70 80 90]


In [1]:
import numpy as np
my_list=[[10,20,30],[40,50,60],[70,80,90]]
matrix=np.array(my_list)
print("elements:")
for row in matrix:
    for ele in row:
        print(ele)

elements:
10
20
30
40
50
60
70
80
90


In [2]:
import numpy as np
my_list=[[10,20,30],[40,50,60],[70,80,90]]
matrix=np.array(my_list)
print("elements:")
for row in matrix:
    for ele in row:
        print(ele,end=' ')
    print()

elements:
10 20 30 
40 50 60 
70 80 90 


In [7]:
import numpy
my_list=[[10,20,30],[40,50,60],[70,80,90]]
matrix=numpy.array(my_list)
print("elements:")
print(matrix)
print()
res=matrix[ : , : ]
print(res)
print()
res=matrix[1:3,1:3]
print(res)
print()

elements:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[[50 60]
 [80 90]]



In [10]:
import numpy
n=int(input("enter size:"))
arr=numpy.ndarray(shape=(n),dtype=int)
print("enter %d elements:" %n)
for i in range(n):
    arr[i]=int(input())
print("Array elements:",arr)

enter size:5
enter 5 elements:
1
2
3
4
5
Array elements: [1 2 3 4 5]


In [11]:
import numpy
m=int(input("enter row size:"))
n=int(input("enter column size"))
matrix=numpy.ndarray(shape=(m,n),dtype=int)
print("size:",matrix.size)
print("shape:",matrix.shape)
print("dimensions:",matrix.ndim)

enter row size:3
enter column size5
size: 15
shape: (3, 5)
dimensions: 2


In [1]:
import numpy
m=int(input("enter row size:"))
n=int(input("enter column size:"))
matrix=numpy.ndarray(shape=(m,n),dtype=int)
print("enter %d elements of %dX%d matrix" %(m*n,m,n))
for i in range(m):
    for j in range(n):
        matrix[i][j]=int(input())
print("%dX%d matrix is:" %(m,n))
print(matrix)

enter row size3
enter column size5
enter 15 elements of 3X5 matrix
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
3X5 matrix is:
[[3 4 5 6 7]
 [8 9 0 1 2]
 [3 4 5 6 7]]


In [2]:
import numpy
arr=numpy.ndarray(shape=(3,3,3),dtype=int)
print("size:",arr.size)
print("datatype",arr.dtype)
print("shape:",arr.shape)
print("dimensions:",arr.ndim)

size: 27
datatype int32
shape: (3, 3, 3)
dimensions: 3


In [3]:
import numpy
arr=numpy.ndarray(shape=(3,3,3),dtype=int)
val=1
x=arr.shape[0]
y=arr.shape[1]
z=arr.shape[2]
for i in range(x):
    for j in range(y):
        for k in range(z):
            arr[i][j][k]=val
            val=val+1
print("array elements:")
print(arr)

array elements:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [6]:
import numpy
arr=numpy.ndarray(shape=(3,3,3),dtype=int)
val=1
x=arr.shape[0]
y=arr.shape[1]
z=arr.shape[2]
for i in range(x):
    for j in range(y):
        for k in range(z):
            arr[i][j][k]=int(input())
            #val=val+1
print("array elements:")
print(arr)

5
6
4
3
2
1
4
5
6
7
8
9
0
9
8
7
6
5
4
3
2
1
2
3
4
5
6
array elements:
[[[5 6 4]
  [3 2 1]
  [4 5 6]]

 [[7 8 9]
  [0 9 8]
  [7 6 5]]

 [[4 3 2]
  [1 2 3]
  [4 5 6]]]
